#!/bin/sh

echo "{\"port\":$RAINBOW_PORT_WEB_UI, \"path\":\"$RAINBOW_WEB_PATH\"}" > /opt/shellinabox/.config

# Clear out admin user before we proceed
if grep -Fq "^admin:" /etc/shadow
then
	userdel -fr admin
fi

exit 0
